DROP TABLE if EXISTS Person CASCADE;

CREATE TABLE Person(
                       pid bigint GENERATED by default as identity,
                       name varchar(255) NOT NULL,
                       age bigint not null,
                       primary key (pid)
);